### PR TITLE
unused VR actionbutton sprites from #37994

### PR DESCRIPTION
**Pull request by MrDoomBringer**
made an actions folder for em

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
we got that merge

**Comment by PKPenguin321** [comment]
only took a month and a year

**Comment by MrDoomBringer** [comment]
@PKPenguin321 how the fuck did you even notice this

**Comment by PKPenguin321** [comment]
image

**Comment by Fikou** [comment]
h

**Pull request merged**
